### ISSUE TITLE
Web scraping for mapahelp.me

### ISSUE THREAD

**Issue by littlepea** [safe-refuge/safeway-data#27]
We've found a great new map-based [source](https://mapahelp.me) of helping points across Europe.

They have an [API endpoint](https://d2916ie68qiajx.cloudfront.net/mapka/organizations) we could consume.

**Comment by moorchegue** [comment]
I'll take this.

**Comment by littlepea** [comment]
Some feedback about Mapahelp issues:
> Duplicated Rows: [454, 1406, 1420, 2059]
> Rows with errors: [46, 76, 161, 247, 251, 464, 756, 891, 913, 921, 951, 1020, 1022, 1024, 1026, 1027, 1411, 1422, 1547, 1599, 1643, 1825, 2034, 2051, 2239, 2318]
