### ISSUE TITLE
Translate country names in English

### ISSUE THREAD

**Issue by littlepea** [safe-refuge/safeway-data#31]
Same as #6 but for contries

I think we should rename `CityTranslator` to `PointTranslator` and make it apply to an arbitrary set of fields.

**Comment by idisblueflash** [comment]
How about we translate the fields: `name`, `address`, and `organizations` together with `country`?
<img width="1450" alt="Screenshot 2022-06-14 at 08 19 18" src="https://user-images.githubusercontent.com/14199/173468034-dd36becb-5931-4308-a9b7-d77b141c7ff9.png">

**Comment by littlepea** [comment]
I don't see too much value in translating `name`, `organizations` or `address`

**Comment by littlepea** [comment]
The main point is translating is not to have everything in English, but rather to achieve consistency in the database, for that all points from the same city/country have the same city/country values.
