### ISSUE TITLE
Dopomoga spider issues

### ISSUE THREAD

**Issue by littlepea** [safe-refuge/safeway-data#35]
We need to map the new categories:
 - LGBTQ+
 - Water
 - Education
 - Jobs

And fix some other issues:

At: dopomoga_enriched.csv, there are two duplicated rows: 20, 22.

Address should be without 'Country' (and without the city). 
Country should be normalized. It should be: "Moldova" or "Republica Moldova" but not both.

**Comment by wdunn001** [comment]
Is this due to the address sanitizer? I believe I am including the city/state/country in the address. (I thought we wanted that)

**Comment by littlepea** [comment]
This is not because of the address sanitizer.

We wanted the city/state/country in the address for geocoding, but not in the final output.

**Comment by moorchegue** [comment]
Address/country/city issue is straightforward. Duplicates are again probably best curated manually.

BTW, they took down this page (where the map was originally embeded): https://dopomoga.gov.md/akkreditovannye-centry-dlya-bezhencev/, now there's a new page: https://dopomoga.gov.md/refugee-accomodation-centre, but it's under construction. The map itself is still accessible and works though.
