### ISSUE TITLE
Normalize URLs in PointOfInterest

### ISSUE THREAD

**Issue by littlepea** [safe-refuge/safeway-data#42]
The url in not in standard format. 
For example: "url": "www.pcpr-limanowa.pl"
It missing the "https://" prefix.

**Comment by idisblueflash** [comment]
For URL has `http://` already, should we keep it as it is?
for example http://www.opsstarysacz.pl/

**Comment by idisblueflash** [comment]
note for myself, need a way to fix this edge case: www.pcpr-jawor.https://sac.mpips.gov.pl:8443/Pomost/CKEditorServlet?TRYB=2





www.pcpr-jawor.https://sac.mpips.gov.pl:8443/Pomost/CKEditorServlet?TRYB=2


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

www.pcpr-jawor.https://sac.mpips.gov.pl:8443/Pomost/CKEditorServlet?TRYB=2


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">


www.pcpr-jawor.https://sac.mpips.gov.pl:8443/Pomost/CKEditorServlet?TRYB=2


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">



www.pcpr-jawor.https://sac.mpips.gov.pl:8443/Pomost/CKEditorServlet?TRYB=2


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by idisblueflash** [comment]
And how about we add a new `point_formatter.UrlFormatter` as below?
```python
class ConvertSpreadsheetData(Injector):
    usecase = convert_data.ConvertSpreadsheetData
    settings = settings.Settings(_env_file="config/.env.example")
    log = print
    spreadsheet_reader = google_sheets.GoogleSheetsReader
    adapter = spreadsheet_adapter.SpreadsheetAdapter
    address_sanitizer = address_sanitizer.AddressSanitizer
    point_formatter = point_formatter.UrlFormatter. # <-- added one
    geocoder = geocoding.GeoCodingProcessor
    translator = translation.PointTranslator
    error_collector = error_collector.ErrorCollector
    validator = composite_validator.CompositeValidator
    validators = [RequiredFieldsValidator(), CategoriesValidator()]
    csv_repository = csv.CSVRepository
```

**Comment by littlepea** [comment]
> For URL has http:// already, should we keep it as it is?

Yes, I think we can keep it as is

**Comment by littlepea** [comment]
> And how about we add a new point_formatter.UrlFormatter as below?

@idisblueflash no need, just add a new validator to the `PointOfInterest` model with `pre=True` (we already have a few) and fix it right there

**Comment by littlepea** [comment]
Some feedback about the Poland scraping data:

> Note that some other URL are funny. 
> Look at rows: [216, 243, 318, 419, 506, 729, 760, 782, 872, 959, 1221, 1446, 1638, 2160, 2388, 2513]
> (row # might be with 1 offset)

**Comment by idisblueflash** [comment]
@littlepea I like to confirm:
1.  for rows[729, 760, 1221, 1446, 2160, 2513], are they really empty, or I miss that URLs data?
2. what should we handle case 506, `www.klwow` , just clean it as ``?

Notes for issues above:
- 216 www.pcpr-jawor.https://sac.mpips.gov.pl:8443/Pomost/CKEditorServlet?TRYB=2
- 243 [www.pcpr.powiatbialski.pl](http://www.pcpr.powiatbialski.pl/)
- 318 [www.pcprzwolen.pl](http://www.pcprzwolen.pl/)
- 419 [www.pcpr.zlotow.pl](http://www.pcpr.zlotow.pl/)
- 506 www.klwow
- 729 
- 760
- 782 [www.swilcza.com.pl](http://www.swilcza.com.pl/) /zakładka Gmina/
- 872 [www.wizajny.naszops.pl](http://www.wizajny.naszops.pl/)
- 959 [www.gopskaliska.pl](http://www.gopskaliska.pl/)
- 1221 
- 1446 
- 1638 http://mgops.polczynzdroj.ibip.pl/
- 2160 
- 2388 [goraswmalgorzaty.pl](http://goraswmalgorzaty.pl/)
- 2513

**Comment by littlepea** [comment]
> for rows[729, 760, 1221, 1446, 2160, 2513], are they really empty, or I miss that URLs data?

If they are empty, that's fine, then we just leave them empty

> what should we handle case 506, www.klwow , just clean it as ``, or we can add a tag Error URL: www.klwow?

just clean it as ``

> how about selecting the first url when we got multiple? 'http://gops.mielec.pl/ ; http://www.gops.ug.mielec.pl/'

Agree

**Comment by idisblueflash** [comment]
>> what should we handle case 506, [www.klwow](http://www.klwow/) , just clean it as ``, or we can add a tag Error URL: [www.klwow](http://www.klwow/)?

> just clean it as ``

I suggest clean email data in URL as `` as well

FYI: Here're some Errors I found:

![Image](https://user-images.githubusercontent.com/14199/174466356-0a6768eb-0d05-46f4-b5e3-79aa9edb240c.png)

**Comment by littlepea** [comment]
> I suggest clean email data in URL as `` as well

Agree
